### PR TITLE
start intro to coding interview

### LINKED ISSUE #1: Add a "Introduction to the Coding Challenge" lesson plan.
## Context

Provide written lesson plans that cover Coding Challenge topics. 
The lessons will anchor workshops, focus on a topic, and train students in some aspect of the Coding Challenge. 
The lesson plan will be shared with the incoming Organizer so they can ramp up quickly. 
Organizers have the flexibility to interpret or add to a lesson plan, when they are leading a workshop. 

**Acceptance Criteria**
- Each lesson plan will focus on one topic.
- Plans will be in the markdown format. 
- Plans will consist of a bullet list and supporting details or facts. 
- The first lesson plan will be "Introduction to Coding Challenge"

### PR DESCRIPTION
**Pull request by boston-code-coffee**
Fixes #1 

This Markdown file is first draft of a "Introduction to the Coding Challenge" lesson plan.

### CODE REVIEW

**Review by parthasarathydNU — COMMENTED** [review]
## Workshop Content Review and Suggestions

After thoroughly reviewing the initial workshop content and reflecting on my notes of the first workshop that I attended, I’ve identified several areas that could further enhance this document. 

Here are my suggestions based on my notes:

	1.	Incorporate Soft Skills Importance: Emphasize the significance of demonstrating interpersonal skills that show participants are not only technically proficient but also great potential team members. This includes effective communication, the art of asking insightful questions, and engaging positively with the interviewer.

	2.	Strategies for Asking Questions: Expand on the section about preparing questions for the interviewer to include strategic questioning—such as clarifying assumptions, inquiring about the use of prebuilt methods, and discussing the preferred programming language. These strategies can significantly impact the interview outcome and demonstrate a candidate’s thoughtful approach.

	3.	Adapting to the Interview Environment: Add content on the importance of practicing in an interview-like online environment. Familiarity with the actual interview IDE can reduce stress and increase coding efficiency during the actual interview.

	4.	Optimal Solution Vs. Completed Solution: Address the dilemma between presenting an optimized solution versus a completed one. Offering strategies to navigate this situation could be invaluable, especially for candidates aiming for senior roles.

	5.	Discussing Complexity and Trade-offs: Encourage a deeper dive into problem-solving strategies by discussing the complexity, trade-offs, and various techniques. This addition could help attendees understand that a high-performance engineer is not only about solving problems but also about analyzing and discussing alternative solutions.

	6.	Daily Practice Over Cramming: Highlight the importance of consistent daily practice over irregular, lengthy cramming sessions. A structured approach to regular problem-solving can build confidence and enhance problem-solving skills more effectively.

	7.	Language and Tech Stack Familiarity Vs. Problem-Solving Skills: Clarify expectations around technical jargon and tech stack familiarity versus the ability to solve problems. Understanding the hiring company’s preferences can help candidates tailor their preparation and focus on what’s most important.

Incorporating these suggestions could make the document more comprehensive. These additions aim to equip participants with a well-rounded preparation strategy, addressing both the technical and interpersonal aspects of coding interviews.

**Comment by boston-code-coffee** [comment]
I added several sections based on the feedback.  
The soft skills sections grew, and so did the clarifying questions. 
This document is starting to get too big to fit in a one-hour intro aimed at a beginner audience. 

We can consider doing a set of more specific "deep dive" talks
I did start two more documents to hold the overflow content.  
Let's discuss at the Saturday standup and solicit user feedback to judge interest.

**Comment by parthasarathydNU** [comment]
I sure agree. We don't want to keep the workshop content too heavy but since we have the content available in the repository, we can use different parts of it during different days. The instructor conducting the workshop that day can speak to their strength and experience. People attending the workshop regularly will gain the entire benefit but nevertheless it will be available on github for them to review.

**Comment by boston-code-coffee** [comment]
merged. Thank you for the feedback. 
I will try an take notes at the next work shop and look for additional material

**Pull request merged**
